name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    name: Build and publish distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip setuptools wheel twine
    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist bdist_wheel
    - name: Publish distribution to PyPI
      run: python -m twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}